apiVersion: v1
kind: Service
metadata:
  name: sukt-apisix-gateway-nodetype
  labels:
    app: sukt-apisix-gateway-nodetype
  namespace: sukt-platform
spec:
  type: NodePort
  selector:
    app: sukt-apisix-gateway
  ports:
  - port: 9080
    name: transfer1
    targetPort: 9080
    nodePort: 30107
  - port: 9443
    name: transfer2
    targetPort: 9443
    nodePort: 30108
