apiVersion: v1
kind: Service
metadata:
  name: nacos-service
  namespace: devops
spec:
  type: NodePort
  selector:
    app: nacos-pod
  ports:
  - port: 8848
    targetPort: 8848
    nodePort: 30104
    name: nacos-port
  - port: 9848
    targetPort: 9848
    nodePort: 30105
    name: nacossynchport
  - port: 9849
    targetPort: 9849
    nodePort: 30106
    name: nacosgrpcport